---
name: Deploy to packagecloud.io
description: 'Deploy debian packages to packagecloud.io'
branding:
  icon: 'cloud-snow'
  color: 'orange'
inputs:
  user:
    description: 'packagecloud.io user; defaults to github repository user'
  repository:
    description: 'packagecloud.io repository'
    required: true
  directory:
    description: 'cd to this directory; used if defined'
    default: ''
  files:
    description: -<
      .deb files to upload. If not specified, all .deb files under the
      current directory are uploaded; if none found, recurse into
      subdirectories.
  upload_dsc:
    description: 'upload *.dsc as well as .deb files'
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
