#!/bin/bash

set -x -e -o pipefail

shopt -s nullglob

if [ -n "$INPUT_USER" ]; then
    user_tmp="$INPUT_USER"
elif [ -n "$GITHUB_REPOSITORY" ]; then
    user_tmp="${GITHUB_REPOSITORY%%/*}"
fi

user=${user_tmp?Please specify a user}
repository=${INPUT_REPOSITORY?Please specify a repository}

# "files" array:
if [ -n "$INPUT_FILES" ]; then
    read -r -a input_files <<<"$INPUT_FILES"

    # Parse pattern matching in input files
    files=()
    for input_file in "${input_files[@]}"; do
        for line in $(compgen -G "${input_file}"); do
            files+=(${line})
        done
    done
else
    # Use all debs in current directory
    files=(*.deb)
    if [ "${#files[@]}" -eq 0 ]; then
        # If no debs found in current, dig deeper
        readarray -d '' files < <(find . -type f -name '*.deb' -print0)
    fi
    if [ "${#files[@]}" -eq 0 ]; then
        # Ok, time to give up
        echo No .deb files found >&2
        exit 1
    fi
fi

dircmd=(:)
if [ -n "$INPUT_DIRECTORY" ]; then
    dircmd=(cd "$INPUT_DIRECTORY")
fi

"${dircmd[@]}"

# Upload each file separately to support multiple file types
for file in "${files[@]}"; do
    package_cloud push "${user}/$repository" "${file}"
done
