#!/bin/bash

if [ -n "$INPUT_USER" ]; then
    user_tmp="$INPUT_USER"
elif [ -n "$GITHUB_REPOSITORY" ]; then
    user_tmp="${GITHUB_REPOSITORY%%/*}"
fi

user=${user_tmp?Please specify a user}
repository=${INPUT_REPOSITORY?Please specify a repository}

# "files" array:
if [ -n "$INPUT_FILES" ]; then
    IFS=' ' read -r -a files <<< "$INPUT_FILES"
else
    readarray -d '' files < <(find . -type f -name '*.deb' -print0)
    if [ "${#files[@]}" -eq 0 ]; then
        echo No .deb files found >&2
        exit 1
    fi
fi

dircmd=( : )
if [ -n "$INPUT_DIRECTORY" ]; then
    dircmd=( cd "$INPUT_DIRECTORY" )
fi

set -x -e -o pipefail

"${dircmd[@]}"

package_cloud push "${user}/$repository" "${files[@]}"
