---
name: CI
on:  # yamllint disable-line rule:truthy
  - push
  - pull_request
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: docker://lpenz/omnilint:0.5.2
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: docker build .
  dockerhub:
    needs: [build, omnilint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.15.1
      - uses: docker/setup-qemu-action@v3.6.0
      - uses: docker/setup-buildx-action@v3.10.0
      - uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6.18.0
        if: steps.version.outputs.version_tagged != ''
        with:
          push: true
          tags: |
            ${{ github.repository }}:${{ steps.version.outputs.version_tagged }}
